name: Publicar no npm

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write  # necessário para OIDC

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: github  # 🔹 nome do ambiente configurado no GitHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          # 🔹 ativa autenticação via OIDC (sem secrets)
          scope: "@Derickcsantos"

      - name: Instalar dependências
        run: npm ci

      - name: Build (opcional)
        run: |
          echo "Nenhuma etapa de build necessária"
          # npm run build (caso use TypeScript no futuro)

      - name: Publicar no npm
        run: npm publish --access public
