name: Publish to npm

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: github

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - run: |
          echo "Nenhuma etapa de build necessária"

      - name: Publish to npm
        run: |
          npm publish --access public || (
            echo "OIDC falhou, tentando com token..."
            npm publish --access public --//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}
          )
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
